api/v1/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from .views import DataSetList, DataSetDetail


dataset_list = DataSetList.as_view({
    'get': 'list',
    'post': 'create'
})
dataset_meta = DataSetList.as_view({
    'get': 'retrieve',
    'put': 'update',
    'delete': 'destroy'
})

urlpatterns = format_suffix_patterns([
    url(r'^datasets/$', dataset_list, name='dataset-list'),
    url(r'^datasets/(?P<pk>[0-9]+)/$', dataset_meta, name='dataset-meta'),
    url(r'^dataset/(?P<pk>[0-9]+)/data/$', DataSetDetail.as_view()),
])

apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views

from .views import SignupView
from .forms import LoginForm


app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name='signup'),

    url(r'^login/$',
        auth_views.login,
        {'template_name': 'accounts/signin.html', 'authentication_form': LoginForm},
        name='auth_login'),

    url(r'^logout/$', auth_views.logout_then_login, name='auth_logout'),

    # url(r'^get_auth_token/', views.obtain_auth_token, name='get_auth_token'),
]

apps/dataset/urls.py
from django.conf.urls import url

from .views import DataSetCreateView, DataSetDetailView


app_name = 'dataset'

urlpatterns = [

    url(r'^create_dataset/$', DataSetCreateView.as_view(), name='create_dataset'),
    url(r'^detail_dataset/(?P<dataset_id>[0-9]+)/$', DataSetDetailView.as_view(), name='detail_dataset'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- fraction_pure_style -->
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/menus.css' %}">
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/menus-core.css' %}">
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/grids.css' %}">
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/fraction_pure_style/tables.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans|Merriweather:700" rel="stylesheet">

    <!-- custome css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Javascript -->
	  <script type="text/javascript" src="{% static 'js/libs/jquery.min.js' %}"></script>

  </head>

  <body>
    <!-- header -->
    {% block header %}
    {% endblock header %}

    <!-- content -->
    {% block content %}
    {% endblock content %}

    {% block extra_script %}{% endblock extra_script %}
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Fraction Data Set{% endblock %}

{% block header %}
  <header>
    <div class="pure-menu pure-menu-horizontal">
      <ul class="pure-menu-list">
          <li class="pure-menu-item pure-menu-selected"><a href="/" class="pure-menu-link">Home</a></li>
          <li class="pure-menu-item pure-menu-selected"><a href="{% url 'accounts:auth_logout' %}" class="pure-menu-link">Logout</a></li>
          <li class="pure-menu-item pure-menu-selected"><a href="{% url 'dataset:create_dataset' %}" class="pure-menu-link">Create Dataset</a></li>
          <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
              <a href="#" id="menuLink1" class="pure-menu-link">My Data</a>
              <ul class="pure-menu-children">
                {% for ds in dataset_list %}
                  <li class="pure-menu-item"><a href="{% url 'dataset:detail_dataset' dataset_id=ds.id %}" class="pure-menu-link"># {{ ds.name }}</a></li>
                {% endfor %}
              </ul>
          </li>
      </ul>
    </div>
  </header>
{% endblock header %}

{% block content %}
<div class="wrap">
    <h1>Instructions</h1>
		<div class="form-main" style="padding: 0; width: 90%; margin: 8% auto">
      <div id="editor" style="height: 480px;font-size: 14px"># 1. Create a new DataSet


import requests
import json

create_url = "{{ host_url }}/api/v1/datasets/"
detail_web_url = "{{ host_url }}/dataset/detail_dataset/%d/"
detail_api_url = "{{ host_url }}/api/v1/dataset/%d/data/"

headers = {
    'Content-Type': "application/json",
    'Authorization': "Token {{ api_token }}",
    'Cache-Control': "no-cache"
    }

payload = {
            "name": "Health Survey",
            "column_names": [{
                "age": "Age of person in years",
                "name": "First and last name",
                "weight": "Weight in pounds",
                "vegetarian": "Is the respondent a vegetarian?"
                }],
            "description": "Conduct a survey asking questions related to health in Townsville."
          }

response = requests.request("POST", create_url, data=json.dumps(payload), headers=headers)

json_resp = json.loads(response.text)

if response.ok:
    print("A Dataset has been created successfully.")
    detail_web_url = detail_web_url % json_resp['pk']
    detail_api_url = detail_api_url % json_resp['pk']

    print("Here is the dataset detail page: %s" % detail_web_url)
    print("Here is the API key URL to pull data: %s" % detail_api_url)

else:
    print("Error in creating dataset.")
    print(response.text)


# 2. Get Detail of a DataSet

import pandas as pd
import json
import requests

url = "{{ host_url }}/api/v1/dataset/1/data/"

headers = {
  'Content-Type': "application/json",
  'Authorization': "Token {{ api_token }}",
  'Cache-Control': "no-cache"
  }

response = requests.request("GET", url, headers=headers)
json_resp = json.loads(response.text)

if response.ok:
  df = pd.DataFrame(json_resp['data'])
  print(df)
else:
  print(response.text)
      </div>
    </div>
</div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'js/libs/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'js/libs/mode-python.js' %}"></script>
<script>
    var editor = ace.edit("editor");
	  editor.setTheme("ace/theme/textmate");

	  var PythonMode = ace.require("ace/mode/python").Mode;
    editor.session.setMode(new PythonMode());
    editor.setOptions({
      readOnly: true
    })
</script>

{% endblock extra_script %}